import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";

import { signInWithGitHub, onAuthStateChanged } from "../firebase";

export default function Home() {
  const [authenticated, setAuthenticated] = useState(false);
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChanged((user) => {
      setUser(user);
      setAuthenticated(true);
    });
  }, []);

  const handleSignInWithGitHub = async () => {
    signInWithGitHub()
      .then((user) => {
        // const { displayName, email, photoURL } = user;
        setUser(user);
        setAuthenticated(true);
      })
      .catch(() => {
        setAuthenticated(false);
      });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="top-0 flex w-full justify-between items-center p-5 shadow">
          <div>
            <h1 className="font-semibold">meetwi</h1>
          </div>
          <div>
            <button>Repositorio</button>
          </div>
        </header>

        <div className="w-full max-w-3xl mt-10 py-5 m-0 mx-auto text-center">
          <h1 className="font-bold text-4xl lg:text-6xl mb-5">
            La plataforma de videoconferencias gratuita
          </h1>
          <p className="text-gray-700 mt-4">
            Con MeetApp podrás crear y unirte a reuniones
          </p>

          <div className="border w-full bg-gray-100 mt-10 py-14">
            {authenticated ? (
              <div>{user.displayName}</div>
            ) : (
              <div className="bg-white w-60 py-10 m-auto my-5 border border-gray-200 rounded-lg">
                <strong className="font-semibold">Únete a Meetwi</strong>
                <button
                  onClick={handleSignInWithGitHub}
                  className="px-6 py-3 mt-5 rounded-md bg-zinc-800 text-zinc-100 text-sm font-medium"
                >
                  Iniciar con GitHub
                </button>
              </div>
            )}
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
